//! Cairn v4 wire protocol.
//!
//! Generated from `proto/cairn/v4/cairn.proto` (package `cairn.v4`).
//! Field numbers 100-199 are reserved in every message (SPEC §18).
//! Handshake negotiates min/max proto version at connect (SPEC §18).

#![forbid(unsafe_code)]

/// Wire + service types generated by tonic/prost from the cairn.v4 proto.
pub mod pb {
    tonic::include_proto!("cairn.v4");
}

/// Current wire protocol version negotiated at Handshake.
/// 5 = StateRecordOp journal arm (ADR-0031 Phase 1). Old clients skip unknown
/// oneof arms and advance their cursor, so this is upgrade-safe — but servers
/// must be upgraded FIRST: an old server drops the unknown arm on decode and
/// would silently record an empty op. Clients tolerate the loss gracefully
/// (records are absent, not corrupt) yet the correct order is server → client.
pub const PROTO_VERSION: i32 = 5;

/// Error codes carried in `ErrorDetail.code` (ADR-0010). Keep in lockstep with docs/ctl-api.md.
pub const ERROR_CODES: &[&str] = &[
    "CONFLICT",
    "STALE_LEASE",
    "REF_CAS",
    "UNAUTHENTICATED",
    "PERMISSION_DENIED",
    "NOT_FOUND",
    "SESSION_EXPIRED",
    "CHECKSUM_MISMATCH",
    "BATCH_TOO_LARGE",
    "RATE_LIMITED",
    "INTERNAL",
    "UNAVAILABLE",
    "COMPACTION_REQUIRED",
    "SESSION_FULL",
];

/// Build a tonic `Status` carrying a structured `ErrorDetail` (never a bare 500, ADR-0010).
pub fn error_status(
    code: &str,
    retry: pb::RetryClass,
    message: impl Into<String>,
) -> tonic::Status {
    let message = message.into();
    let detail = pb::ErrorDetail {
        code: code.to_string(),
        retry: retry as i32,
        message: message.clone(),
    };
    let json = format!(
        r#"{{"code":"{}","retry":{},"message":{}}}"#,
        detail.code,
        detail.retry,
        serde_json::to_string(&detail.message).unwrap_or_else(|_| "\"\"".into())
    );
    tonic::Status::with_details(grpc_code_for(retry), message, bytes::Bytes::from(json))
}

fn grpc_code_for(retry: pb::RetryClass) -> tonic::Code {
    use tonic::Code;
    match retry {
        pb::RetryClass::RetryAuto => Code::Unavailable,
        pb::RetryClass::RetryNever => Code::FailedPrecondition,
        pb::RetryClass::RetryConflict => Code::Aborted,
        pb::RetryClass::RetryServer => Code::Internal,
        pb::RetryClass::Unspecified => Code::Unknown,
    }
}

/// Extract a structured `ErrorDetail` from a tonic `Status` (falls back to INTERNAL).
pub fn error_detail(status: &tonic::Status) -> pb::ErrorDetail {
    let raw = status.details();
    if let Ok(v) = serde_json::from_slice::<serde_json::Value>(raw) {
        if let Some(code) = v["code"].as_str() {
            return pb::ErrorDetail {
                code: code.to_string(),
                retry: v["retry"].as_i64().unwrap_or(4) as i32,
                message: v["message"].as_str().unwrap_or_default().to_string(),
            };
        }
    }
    pb::ErrorDetail {
        code: "INTERNAL".into(),
        retry: pb::RetryClass::RetryServer as i32,
        message: status.message().to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pb::JournalOp;
    use prost::Message as _;

    #[test]
    fn error_roundtrip() {
        let st = error_status("CONFLICT", pb::RetryClass::RetryConflict, "path diverged");
        let d = error_detail(&st);
        assert_eq!(d.code, "CONFLICT");
        assert_eq!(d.retry, pb::RetryClass::RetryConflict as i32);
        assert_eq!(d.message, "path diverged");
    }

    #[test]
    fn every_documented_code_maps() {
        assert!(ERROR_CODES.contains(&"STALE_LEASE"));
    }

    /// ADR-0031 Phase 1: the state_record arm must survive encode/decode as a
    /// logical fixed point (byte-exactness is NOT a prost guarantee — see the
    /// fuzz target's contract comment).
    #[test]
    fn state_record_op_roundtrips() {
        let op = JournalOp {
            op: Some(pb::journal_op::Op::StateRecord(pb::StateRecordOp {
                family: "member".into(),
                key: "dev-abc123".into(),
                payload: br#"{"device_id":"dev-abc123","role":"editor"}"#.to_vec(),
                ts_ms: 1_724_800_000_000,
                tombstone: false,
            })),
        };
        let mut buf = Vec::new();
        op.encode(&mut buf).unwrap();
        let back = JournalOp::decode(buf.as_slice()).unwrap();
        assert_eq!(back, op, "decode/encode/decode must be a fixed point");
        match back.op.as_ref().unwrap() {
            pb::journal_op::Op::StateRecord(sr) => {
                assert_eq!(sr.family, "member");
                assert_eq!(sr.key, "dev-abc123");
                assert_eq!(sr.ts_ms, 1_724_800_000_000);
                assert!(!sr.tombstone);
                assert!(String::from_utf8(sr.payload.clone()).is_ok());
            }
            other => panic!("expected StateRecord arm, got {other:?}"),
        }
        // tombstone variant survives too (the Phase-2 revoke substrate)
        let tomb = JournalOp {
            op: Some(pb::journal_op::Op::StateRecord(pb::StateRecordOp {
                family: "review_link".into(),
                key: "0123456789abcdef0123456789abcdef".into(),
                payload: Vec::new(),
                ts_ms: 1,
                tombstone: true,
            })),
        };
        let mut buf = Vec::new();
        tomb.encode(&mut buf).unwrap();
        assert_eq!(JournalOp::decode(buf.as_slice()).unwrap(), tomb);
    }
}
