//! Cairn v4 wire protocol.
//!
//! Generated from `proto/cairn/v4/cairn.proto` (package `cairn.v4`).
//! Field numbers 100-199 are reserved in every message (SPEC §18).
//! Handshake negotiates min/max proto version at connect (SPEC §18).

#![forbid(unsafe_code)]

/// Wire + service types generated by tonic/prost from the cairn.v4 proto.
pub mod pb {
    tonic::include_proto!("cairn.v4");
}

/// Current wire protocol version negotiated at Handshake.
pub const PROTO_VERSION: i32 = 4;

/// Error codes carried in `ErrorDetail.code` (ADR-0010). Keep in lockstep with docs/ctl-api.md.
pub const ERROR_CODES: &[&str] = &[
    "CONFLICT",
    "STALE_LEASE",
    "REF_CAS",
    "UNAUTHENTICATED",
    "PERMISSION_DENIED",
    "NOT_FOUND",
    "SESSION_EXPIRED",
    "CHECKSUM_MISMATCH",
    "BATCH_TOO_LARGE",
    "RATE_LIMITED",
    "INTERNAL",
    "UNAVAILABLE",
    "COMPACTION_REQUIRED",
    "SESSION_FULL",
];

/// Build a tonic `Status` carrying a structured `ErrorDetail` (never a bare 500, ADR-0010).
pub fn error_status(
    code: &str,
    retry: pb::RetryClass,
    message: impl Into<String>,
) -> tonic::Status {
    let message = message.into();
    let detail = pb::ErrorDetail {
        code: code.to_string(),
        retry: retry as i32,
        message: message.clone(),
    };
    let json = format!(
        r#"{{"code":"{}","retry":{},"message":{}}}"#,
        detail.code,
        detail.retry,
        serde_json::to_string(&detail.message).unwrap_or_else(|_| "\"\"".into())
    );
    tonic::Status::with_details(grpc_code_for(retry), message, bytes::Bytes::from(json))
}

fn grpc_code_for(retry: pb::RetryClass) -> tonic::Code {
    use tonic::Code;
    match retry {
        pb::RetryClass::RetryAuto => Code::Unavailable,
        pb::RetryClass::RetryNever => Code::FailedPrecondition,
        pb::RetryClass::RetryConflict => Code::Aborted,
        pb::RetryClass::RetryServer => Code::Internal,
        pb::RetryClass::Unspecified => Code::Unknown,
    }
}

/// Extract a structured `ErrorDetail` from a tonic `Status` (falls back to INTERNAL).
pub fn error_detail(status: &tonic::Status) -> pb::ErrorDetail {
    let raw = status.details();
    if let Ok(v) = serde_json::from_slice::<serde_json::Value>(raw) {
        if let Some(code) = v["code"].as_str() {
            return pb::ErrorDetail {
                code: code.to_string(),
                retry: v["retry"].as_i64().unwrap_or(4) as i32,
                message: v["message"].as_str().unwrap_or_default().to_string(),
            };
        }
    }
    pb::ErrorDetail {
        code: "INTERNAL".into(),
        retry: pb::RetryClass::RetryServer as i32,
        message: status.message().to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn error_roundtrip() {
        let st = error_status("CONFLICT", pb::RetryClass::RetryConflict, "path diverged");
        let d = error_detail(&st);
        assert_eq!(d.code, "CONFLICT");
        assert_eq!(d.retry, pb::RetryClass::RetryConflict as i32);
        assert_eq!(d.message, "path diverged");
    }

    #[test]
    fn every_documented_code_maps() {
        assert!(ERROR_CODES.contains(&"STALE_LEASE"));
    }
}
