//! Golden corpus: one base/ours/theirs triple per class C0–C10, committed as
//! fixtures (ADR-0015 §7). Every case asserts the expected verdict AND the
//! merged output shape — the regression contract for the whole merge.
//!
//! Fixture policy (§7, honest labeling): all triples here are SYNTHETIC
//! (generated by this test, written as files at review time would duplicate
//! what the code constructs); the two REAL-format fixtures
//! (roundtrip_base.otio / roundtrip_python.otio) come from python-otio
//! 0.18.1 and pin the interop contract separately.

use cairn_tl::classifier::class;
use cairn_tl::merge::{merge, Outcome};
use cairn_tl::model::*;
use cairn_tl::rational::Rational;

fn tv(v: i128, r: i128) -> TimeVal {
    TimeVal {
        value: Rational::new(v, 1).unwrap(),
        rate: Rational::new(r, 1).unwrap(),
    }
}

fn clip(name: &str, url: &str, start: i128, dur: i128) -> Element {
    let mut c = Element::leaf(Kind::Clip, name);
    c.media = Some(MediaRef::single(
        MediaKind::External,
        String::new(),
        Some(url.into()),
    ));
    c.source_range = Some(TimeRange {
        start: tv(start, 24),
        duration: tv(dur, 24),
    });
    c
}

fn doc(items: Vec<Element>) -> Timeline {
    Timeline {
        name: "golden".into(),
        global_start_time: None,
        metadata: JsonMap::new(),
        tracks: Element::container(
            Kind::Stack,
            "tracks",
            vec![Element::container(
                Kind::Track(TrackKind::Video),
                "V1",
                items,
            )],
        ),
        extra: JsonMap::new(),
    }
}

fn stamp(tl: &mut Timeline) {
    tl.walk_mut(|e| {
        if e.cairn_uuid().is_none() {
            let id = uuid::Uuid::now_v7().to_string();
            e.stamp_uuid(&id);
        }
    });
}

/// C0 — one-sided edit: auto-apply, other side untouched.
#[test]
fn golden_c0_one_sided() {
    let mut base = doc(vec![clip("A", "a", 0, 24), clip("B", "b", 0, 24)]);
    stamp(&mut base);
    let mut ours = base.clone();
    let mut theirs = base.clone();
    ours.tracks.children[0].children[0].name = "A2".into();
    theirs.tracks.children[0].children[1].enabled = false;
    let (merged, report) = merge(&base, &ours, &theirs).unwrap();
    assert_eq!(report.outcome, Outcome::Clean);
    let items = &merged.tracks.children[0].children;
    assert_eq!(items[0].name, "A2");
    assert!(!items[1].enabled);
    // zero interacting pairs → histogram empty
    assert!(report.histogram.is_empty());
}

/// C1 — MARKER_ADD on both sides: union (ours order, then theirs).
#[test]
fn golden_c1_marker_union() {
    let mut base = doc(vec![clip("A", "a", 0, 24)]);
    stamp(&mut base);
    let mk = |name: &str| Marker {
        schema: "Marker.2".into(),
        name: name.into(),
        color: "RED".into(),
        comment: String::new(),
        marked_range: TimeRange {
            start: tv(1, 24),
            duration: tv(0, 24),
        },
        metadata: JsonMap::new(),
        extra: JsonMap::new(),
    };
    let mut ours = base.clone();
    let mut theirs = base.clone();
    ours.tracks.children[0].children[0]
        .markers
        .push(mk("ours-marker"));
    theirs.tracks.children[0].children[0]
        .markers
        .push(mk("theirs-marker"));
    let (merged, report) = merge(&base, &ours, &theirs).unwrap();
    assert_eq!(report.outcome, Outcome::Clean);
    assert_eq!(report.histogram.get(&class::C1), Some(&1));
    let names: Vec<&str> = merged.tracks.children[0].children[0]
        .markers
        .iter()
        .map(|m| m.name.as_str())
        .collect();
    assert_eq!(names, ["ours-marker", "theirs-marker"]);
}

/// C2 — ATTR same element, different keys: both apply.
#[test]
fn golden_c2_attr_different_keys() {
    let mut base = doc(vec![clip("A", "a", 0, 24)]);
    stamp(&mut base);
    let mut ours = base.clone();
    let mut theirs = base.clone();
    ours.tracks.children[0].children[0].name = "A2".into();
    theirs.tracks.children[0].children[0].enabled = false;
    let (merged, report) = merge(&base, &ours, &theirs).unwrap();
    assert_eq!(report.outcome, Outcome::Clean);
    assert_eq!(report.histogram.get(&class::C2), Some(&1));
    let el = &merged.tracks.children[0].children[0];
    assert_eq!(el.name, "A2");
    assert!(!el.enabled);
}

/// C3 — ATTR same element, same key, different values: HUMAN (base kept).
#[test]
fn golden_c3_attr_same_key_conflict() {
    let mut base = doc(vec![clip("A", "a", 0, 24)]);
    stamp(&mut base);
    let mut ours = base.clone();
    let mut theirs = base.clone();
    ours.tracks.children[0].children[0].name = "OursName".into();
    theirs.tracks.children[0].children[0].name = "TheirsName".into();
    let (merged, report) = merge(&base, &ours, &theirs).unwrap();
    assert_eq!(report.outcome, Outcome::Conflicts);
    assert_eq!(report.histogram.get(&class::C3), Some(&1));
    assert_eq!(
        merged.tracks.children[0].children[0].name, "A",
        "base value kept — no LWW"
    );
}

/// C4 — MOVE vs MOVE, different targets: HUMAN (base positions kept).
#[test]
fn golden_c4_move_move_conflict() {
    let mut base = doc(vec![
        clip("A", "a", 0, 24),
        clip("B", "b", 0, 24),
        clip("C", "c", 0, 24),
    ]);
    stamp(&mut base);
    // ours: A to the end. theirs: A before C (different target).
    let mut ours = base.clone();
    let mut theirs = base.clone();
    let a = ours.tracks.children[0].children.remove(0);
    ours.tracks.children[0].children.push(a);
    let a = theirs.tracks.children[0].children.remove(0);
    theirs.tracks.children[0].children.insert(1, a);
    let (merged, report) = merge(&base, &ours, &theirs).unwrap();
    assert_eq!(report.outcome, Outcome::Conflicts);
    assert_eq!(report.histogram.get(&class::C4), Some(&1));
    let names: Vec<&str> = merged.tracks.children[0]
        .children
        .iter()
        .map(|e| e.name.as_str())
        .collect();
    assert_eq!(
        names,
        ["A", "B", "C"],
        "both moves withheld — base order kept"
    );
}

/// C5 — MOVE vs TRIM same element: auto, move then trim (commutes exactly).
#[test]
fn golden_c5_move_trim_commuting() {
    let mut base = doc(vec![clip("A", "a", 0, 24), clip("B", "b", 0, 24)]);
    stamp(&mut base);
    let mut ours = base.clone();
    let mut theirs = base.clone();
    let b = ours.tracks.children[0].children.remove(1);
    ours.tracks.children[0].children.insert(0, b);
    theirs.tracks.children[0].children[1].source_range = Some(TimeRange {
        start: tv(0, 24),
        duration: tv(12, 24),
    });
    let (merged, report) = merge(&base, &ours, &theirs).unwrap();
    assert_eq!(report.outcome, Outcome::Clean);
    assert_eq!(report.histogram.get(&class::C5), Some(&1));
    let items = &merged.tracks.children[0].children;
    let names: Vec<&str> = items.iter().map(|e| e.name.as_str()).collect();
    assert_eq!(names, ["B", "A"]);
    assert_eq!(
        items[0].source_range.as_ref().unwrap().duration.value.num,
        12
    );
}

/// C6 — REMOVE on both sides: auto (removed once).
#[test]
fn golden_c6_remove_both() {
    let mut base = doc(vec![clip("A", "a", 0, 24), clip("B", "b", 0, 24)]);
    stamp(&mut base);
    let mut ours = base.clone();
    let mut theirs = base.clone();
    ours.tracks.children[0].children.remove(0);
    theirs.tracks.children[0].children.remove(0);
    let (merged, report) = merge(&base, &ours, &theirs).unwrap();
    assert_eq!(report.outcome, Outcome::Clean);
    assert_eq!(report.histogram.get(&class::C6), Some(&1));
    assert_eq!(merged.tracks.children[0].children.len(), 1);
    assert_eq!(merged.tracks.children[0].children[0].name, "B");
}

/// C7 — REMOVE (one side) vs TRIM/ATTR/MOVE (other): HUMAN (deletion-wins
/// is not safe for creative work — the withheld element survives).
#[test]
fn golden_c7_remove_vs_edit() {
    let mut base = doc(vec![clip("A", "a", 0, 24), clip("B", "b", 0, 24)]);
    stamp(&mut base);
    let mut ours = base.clone();
    let mut theirs = base.clone();
    ours.tracks.children[0].children.remove(1);
    theirs.tracks.children[0].children[1].source_range = Some(TimeRange {
        start: tv(0, 24),
        duration: tv(12, 24),
    });
    let (merged, report) = merge(&base, &ours, &theirs).unwrap();
    assert_eq!(report.outcome, Outcome::Conflicts);
    assert_eq!(report.histogram.get(&class::C7), Some(&1));
    let items = &merged.tracks.children[0].children;
    assert_eq!(items.len(), 2, "withheld removal keeps B");
    assert_eq!(
        items[1].source_range.as_ref().unwrap().duration.value.num,
        24,
        "withheld trim keeps base duration"
    );
}

/// C8 — INSERT both sides at the same (track, index), different content:
/// auto-with-note (ours at index, theirs immediately after).
#[test]
fn golden_c8_insert_same_slot() {
    let mut base = doc(vec![clip("A", "a", 0, 24), clip("B", "b", 0, 24)]);
    stamp(&mut base);
    let mut ours = base.clone();
    let mut theirs = base.clone();
    ours.tracks.children[0].children.insert(1, {
        let mut c = clip("O", "o", 0, 24);
        c.stamp_uuid("u-o");
        c
    });
    theirs.tracks.children[0].children.insert(1, {
        let mut c = clip("T", "t", 0, 24);
        c.stamp_uuid("u-t");
        c
    });
    let (merged, report) = merge(&base, &ours, &theirs).unwrap();
    assert_eq!(report.outcome, Outcome::Notes);
    assert_eq!(report.histogram.get(&class::C8), Some(&1));
    let names: Vec<&str> = merged.tracks.children[0]
        .children
        .iter()
        .map(|e| e.name.as_str())
        .collect();
    assert_eq!(names, ["A", "O", "T", "B"]);
}

/// C9 — TRACK_REMOVE vs any op inside that track: HUMAN.
#[test]
fn golden_c9_track_remove_vs_inside() {
    let mut base = doc(vec![clip("A", "a", 0, 24)]);
    stamp(&mut base);
    // theirs adds a second track with a clip; ours removes... build richer:
    let mut richer = doc(vec![clip("A", "a", 0, 24), clip("B", "b", 0, 24)]);
    stamp(&mut richer);
    let mut ours = richer.clone();
    let mut theirs = richer.clone();
    // ours removes the whole (only) track
    ours.tracks.children.clear();
    // theirs trims A inside it
    theirs.tracks.children[0].children[0].source_range = Some(TimeRange {
        start: tv(0, 24),
        duration: tv(12, 24),
    });
    let (_merged, report) = merge(&richer, &ours, &theirs).unwrap();
    assert_eq!(report.outcome, Outcome::Conflicts);
    assert_eq!(report.histogram.get(&class::C9), Some(&1));
    let c9 = report
        .verdicts
        .iter()
        .find(|v| v.class == class::C9)
        .unwrap();
    assert!(c9.note.contains("track removal"));
}

/// C10 — structural mismatch: positional-identity element moved → refuse.
#[test]
fn golden_c10_refuse_on_ladder_collapse() {
    let blank = Element::leaf(Kind::Gap, "");
    let mut x = clip("X", "x", 0, 24);
    x.stamp_uuid("u-x");
    let base = doc(vec![x, blank]);
    let mut side = base.clone();
    let items = &mut side.tracks.children[0].children;
    let one = items.remove(0);
    items.push(one);
    let err = merge(&base, &side, &base.clone()).unwrap_err();
    assert!(
        err.0.starts_with("C10"),
        "refusal must carry the C10 class: {}",
        err.0
    );
}

/// Determinism property on the golden corpus: same inputs → same output bytes.
#[test]
fn golden_determinism_bytes() {
    let mut base = doc(vec![clip("A", "a", 0, 24), clip("B", "b", 0, 24)]);
    stamp(&mut base);
    let mut ours = base.clone();
    let mut theirs = base.clone();
    ours.tracks.children[0].children[0].name = "A2".into();
    theirs.tracks.children[0].children[1].enabled = false;
    let (m1, r1) = merge(&base, &ours, &theirs).unwrap();
    let (m2, r2) = merge(&base, &ours, &theirs).unwrap();
    assert_eq!(
        cairn_tl::canon::serialize(&m1).unwrap(),
        cairn_tl::canon::serialize(&m2).unwrap()
    );
    assert_eq!(r1.to_json().to_string(), r2.to_json().to_string());
}

/// Mirror-stability (ADR §7): verdicts are ours/theirs-swap-stable — the same
/// PAIRS classify to the same classes with sides exchanged (roles differ, the
/// CONFLICT SET does not).
#[test]
fn golden_verdict_mirror_stability() {
    let mut base = doc(vec![clip("A", "a", 0, 24)]);
    stamp(&mut base);
    let mut ours = base.clone();
    let mut theirs = base.clone();
    ours.tracks.children[0].children[0].name = "Ours".into();
    theirs.tracks.children[0].children[0].name = "Theirs".into();
    let (_, r1) = merge(&base, &ours, &theirs).unwrap();
    let (_, r2) = merge(&base, &theirs, &ours).unwrap();
    assert_eq!(r1.outcome, r2.outcome);
    assert_eq!(r1.histogram, r2.histogram, "class histogram is swap-stable");
}
