//! Review session model: the version stack, guest links, and the
//! operations on them. Pure data + pure functions — persistence lives in
//! [`crate::store`], serving in [`crate::http`].

use serde::{Deserialize, Serialize};

/// What a guest link allows: `Commenter` is the default review role (view,
/// frame-accurate comments, resolve); `Viewer` is present-mode (view only,
/// no writes through the portal); `Studio` (ADR-0028 §E) is a team link —
/// it comments AND sees `internal` notes, so the client-facing filter and
/// the studio view are the same endpoint with different audiences.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum GuestRole {
    Commenter,
    Viewer,
    Studio,
}

impl GuestRole {
    pub fn as_str(self) -> &'static str {
        match self {
            GuestRole::Commenter => "commenter",
            GuestRole::Viewer => "viewer",
            GuestRole::Studio => "studio",
        }
    }

    pub fn parse(s: &str) -> Option<GuestRole> {
        match s {
            "commenter" => Some(GuestRole::Commenter),
            "viewer" => Some(GuestRole::Viewer),
            "studio" | "team" => Some(GuestRole::Studio),
            _ => None,
        }
    }

    /// Whether this role may write comments / resolve through the portal.
    pub fn can_comment(self) -> bool {
        matches!(self, GuestRole::Commenter | GuestRole::Studio)
    }

    /// Whether this link's audience may receive `internal` notes
    /// (ADR-0028 §E). Enforcement is server-side: the session handler
    /// filters BEFORE serialization, so a client link never receives
    /// the bytes at all.
    pub fn sees_internal(self) -> bool {
        matches!(self, GuestRole::Studio)
    }
}

/// One entry in the version stack. Append-only: publishing never mutates a
/// prior version (clients reviewing v3 must never see v3 silently become
/// v4 — that is the whole point of stacking).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReviewVersion {
    /// Stack position, 1-based, ascending.
    pub number: u32,
    /// Human label, e.g. "v3 — picture lock candidate".
    pub label: String,
    /// Media file relative to the project root (the watchable cut).
    pub media_rel: String,
    /// Optional lightweight proxy relative path (generated by the proxy
    /// pipeline, ADR-0020 §3) — remote guests stream this first.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proxy_rel: Option<String>,
    /// Frames per second as an exact rational (24000/1001 for 23.976).
    pub fps_num: u32,
    pub fps_den: u32,
    /// Total frames of the cut (frame-accurate duration).
    pub frames: u64,
    /// Content fingerprint of the source timeline at publish time (the
    /// cairn-tl element fingerprint) — binds the review cut to the exact
    /// timeline revision, which the AAF/OMF handoff ledger verifies
    /// against (ADR-0020 §6).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeline_fingerprint: Option<String>,
    /// Optional snapshot/commit hash the version was published from.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub snapshot: Option<String>,
    pub published_by: String,
    /// Unix millis.
    pub published_at: i64,
}

impl ReviewVersion {
    /// fps as f64 (display only; anchors stay integer frames).
    pub fn fps(&self) -> f64 {
        f64::from(self.fps_num) / f64::from(self.fps_den.max(1))
    }

    /// The integer timecode rate (24/25/30 basis; NDF convention — the
    /// notes timecode helper divides by an integer rate). 23.976 counts
    /// on the 24 basis, 29.97 on the 30 basis; exotic rates use their
    /// nearest integer.
    pub fn tc_rate(&self) -> i128 {
        let f = self.fps();
        if (f - 23.976).abs() < 0.75 {
            24
        } else if (f - 29.97).abs() < 0.75 {
            30
        } else {
            f.round().max(1.0) as i128
        }
    }

    /// `HH:MM:SS:FF` for a frame index in this version (NDF).
    pub fn timecode(&self, frame: u64) -> String {
        cairn_tl::notes::csv::timecode(i128::from(frame), self.tc_rate())
    }

    /// Which media the guest should stream: proxy when present, else the
    /// media file.
    pub fn stream_rel(&self) -> &str {
        match &self.proxy_rel {
            Some(p) => p.as_str(),
            None => self.media_rel.as_str(),
        }
    }
}

/// A share link. The token is the identity: 32 hex chars from a uuid v4
/// (122 bits of OS CSPRNG) — guessable is not a thing, and there is no
/// account to phish. Expiry is enforced at every read.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct GuestLink {
    pub token: String,
    pub role: GuestRole,
    /// Who this link is for ("Acme client — Jane"), display only.
    #[serde(default)]
    pub note: String,
    /// Unix millis; 0 = no expiry.
    pub expires_at: i64,
    /// View-only links to the newest version (no stack selector).
    #[serde(default)]
    pub latest_only: bool,
    pub created_at: i64,
}

impl GuestLink {
    /// Generate a fresh link token (uuid v4 simple — 122 CSPRNG bits).
    pub fn new_token() -> String {
        uuid::Uuid::new_v4().simple().to_string()
    }

    pub fn is_expired(&self, now_ms: i64) -> bool {
        self.expires_at > 0 && now_ms >= self.expires_at
    }

    /// Resolve a session's link by token, rejecting unknown or expired
    /// tokens (fail closed).
    pub fn resolve<'a>(links: &'a [GuestLink], token: &str, now_ms: i64) -> Option<&'a GuestLink> {
        links
            .iter()
            .find(|l| l.token == token)
            .filter(|l| !l.is_expired(now_ms))
    }
}

/// The persisted session: `.cairn/review.json`. Deterministic ordering
/// (versions ascending, links by creation) so peer sync converges.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReviewFile {
    pub schema: String,
    pub title: String,
    /// Append-only stack.
    pub versions: Vec<ReviewVersion>,
    pub links: Vec<GuestLink>,
}

pub const SCHEMA: &str = "cairn-review/v1";

impl Default for ReviewFile {
    fn default() -> Self {
        ReviewFile {
            schema: SCHEMA.into(),
            title: String::new(),
            versions: Vec::new(),
            links: Vec::new(),
        }
    }
}

impl ReviewFile {
    /// Canonical JSON bytes (pretty + stable field order).
    pub fn to_json(&self) -> Result<Vec<u8>, String> {
        serde_json::to_vec_pretty(self).map_err(|e| format!("serialize review: {e}"))
    }

    pub fn from_json(bytes: &[u8]) -> Result<ReviewFile, String> {
        let f: ReviewFile =
            serde_json::from_slice(bytes).map_err(|e| format!("parse review: {e}"))?;
        if f.schema != SCHEMA {
            return Err(format!("unknown review schema: {}", f.schema));
        }
        Ok(f)
    }

    /// The newest version (what a landing client should review).
    pub fn latest(&self) -> Option<&ReviewVersion> {
        self.versions.last()
    }

    /// Versions a link may see: everything, or the latest only.
    pub fn versions_for(&self, link: &GuestLink) -> Vec<&ReviewVersion> {
        if link.latest_only {
            self.latest().into_iter().collect()
        } else {
            self.versions.iter().collect()
        }
    }

    /// Append a version. Stack positions are assigned (input `number` is
    /// ignored — the stack defines the order, callers cannot overwrite
    /// history), and append-only is enforced by returning the new number.
    pub fn publish(&mut self, mut v: ReviewVersion) -> u32 {
        v.number = self.versions.last().map(|p| p.number + 1).unwrap_or(1);
        v.published_at = v.published_at.max(0);
        let n = v.number;
        self.versions.push(v);
        n
    }

    /// Add a guest link with a fresh token; returns the token.
    pub fn add_link(
        &mut self,
        role: GuestRole,
        note: String,
        ttl_ms: i64,
        latest_only: bool,
        now_ms: i64,
    ) -> String {
        let link = GuestLink {
            token: GuestLink::new_token(),
            role,
            note,
            expires_at: if ttl_ms > 0 { now_ms + ttl_ms } else { 0 },
            latest_only,
            created_at: now_ms,
        };
        let t = link.token.clone();
        self.links.push(link);
        t
    }

    /// Drop expired links (housekeeping; returns how many).
    pub fn prune_links(&mut self, now_ms: i64) -> usize {
        let before = self.links.len();
        self.links.retain(|l| !l.is_expired(now_ms));
        before - self.links.len()
    }

    /// Look up a version by stack number.
    pub fn version(&self, number: u32) -> Option<&ReviewVersion> {
        self.versions.iter().find(|v| v.number == number)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn now() -> i64 {
        1_700_000_000_000
    }

    fn version(media: &str, fps: (u32, u32), frames: u64) -> ReviewVersion {
        ReviewVersion {
            number: 0,
            label: "cut".into(),
            media_rel: media.into(),
            proxy_rel: None,
            fps_num: fps.0,
            fps_den: fps.1,
            frames,
            timeline_fingerprint: None,
            snapshot: None,
            published_by: "editor-a".into(),
            published_at: now(),
        }
    }

    #[test]
    fn stack_is_append_only_and_positions_assigned() {
        let mut f = ReviewFile {
            title: "Brand Film".into(),
            ..Default::default()
        };
        assert_eq!(f.publish(version("cuts/v1.mp4", (24, 1), 2400)), 1);
        assert_eq!(f.publish(version("cuts/v2.mp4", (24, 1), 2520)), 2);
        // even if the caller claims number 99, the stack decides
        let mut v99 = version("cuts/v3.mp4", (24, 1), 2600);
        v99.number = 99;
        assert_eq!(f.publish(v99), 3);
        assert_eq!(
            f.versions.iter().map(|v| v.number).collect::<Vec<_>>(),
            [1, 2, 3]
        );
        assert_eq!(f.latest().unwrap().media_rel, "cuts/v3.mp4");
    }

    #[test]
    fn timecode_math_across_rates() {
        let v24 = version("a.mp4", (24, 1), 0);
        assert_eq!(v24.timecode(0), "00:00:00:00");
        assert_eq!(v24.timecode(23), "00:00:00:23");
        assert_eq!(v24.timecode(24), "00:00:01:00");
        assert_eq!(v24.timecode(24 * 60 + 11), "00:01:00:11");
        // 23.976 uses the 24 basis (NDF)
        let v23976 = version("b.mp4", (24000, 1001), 0);
        assert_eq!(v23976.tc_rate(), 24);
        assert_eq!(v23976.timecode(48), "00:00:02:00");
        // 29.97 uses the 30 basis
        let v2997 = version("c.mp4", (30000, 1001), 0);
        assert_eq!(v2997.tc_rate(), 30);
        assert_eq!(v2997.timecode(59), "00:00:01:29");
        assert_eq!(v2997.timecode(30), "00:00:01:00");
        // 25 stays 25
        let v25 = version("d.mp4", (25, 1), 0);
        assert_eq!(v25.tc_rate(), 25);
        assert_eq!(v25.timecode(75), "00:00:03:00");
    }

    #[test]
    fn stream_prefers_proxy() {
        let mut v = version("media/big.mov", (24, 1), 100);
        assert_eq!(v.stream_rel(), "media/big.mov");
        v.proxy_rel = Some("proxies/big.mp4".into());
        assert_eq!(v.stream_rel(), "proxies/big.mp4");
    }

    #[test]
    fn guest_tokens_are_unique_and_well_shaped() {
        let a = GuestLink::new_token();
        let b = GuestLink::new_token();
        assert_ne!(a, b);
        assert_eq!(a.len(), 32);
        assert!(a.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn links_fail_closed_on_unknown_and_expired() {
        let mut f = ReviewFile::default();
        let t = f.add_link(GuestRole::Commenter, "jane".into(), 3_600_000, false, now());
        let t2 = f.add_link(GuestRole::Viewer, "expired".into(), 1, false, now());
        // unknown token
        assert!(GuestLink::resolve(&f.links, "deadbeef", now()).is_none());
        // valid
        assert_eq!(GuestLink::resolve(&f.links, &t, now()).unwrap().token, t);
        // expired (ttl 1ms, now advanced)
        assert!(GuestLink::resolve(&f.links, &t2, now() + 10).is_none());
        // never-expiring link survives
        let t3 = f.add_link(GuestRole::Viewer, "forever".into(), 0, true, now());
        assert!(GuestLink::resolve(&f.links, &t3, now() + 10_000_000).is_some());
        // housekeeping
        assert_eq!(f.prune_links(now() + 10), 1);
        assert_eq!(f.links.len(), 2);
    }

    #[test]
    fn roles_gate_commenting() {
        assert!(GuestRole::Commenter.can_comment());
        assert!(!GuestRole::Viewer.can_comment());
        assert!(GuestRole::Studio.can_comment(), "studio links write too");
        assert!(!GuestRole::Commenter.sees_internal());
        assert!(!GuestRole::Viewer.sees_internal());
        assert!(
            GuestRole::Studio.sees_internal(),
            "studio sees internal notes"
        );
        assert_eq!(GuestRole::parse("viewer"), Some(GuestRole::Viewer));
        assert_eq!(GuestRole::parse("studio"), Some(GuestRole::Studio));
        assert_eq!(GuestRole::parse("nope"), None);
    }

    #[test]
    fn latest_only_links_see_one_version() {
        let mut f = ReviewFile::default();
        f.publish(version("v1.mp4", (24, 1), 10));
        f.publish(version("v2.mp4", (24, 1), 20));
        let t = f.add_link(GuestRole::Viewer, "x".into(), 0, true, now());
        let link = f.links.iter().find(|l| l.token == t).unwrap();
        let seen = f.versions_for(link);
        assert_eq!(seen.len(), 1);
        assert_eq!(seen[0].media_rel, "v2.mp4");
        let full = f.add_link(GuestRole::Commenter, "y".into(), 0, false, now());
        let l2 = f.links.iter().find(|l| l.token == full).unwrap();
        assert_eq!(f.versions_for(l2).len(), 2);
    }

    #[test]
    fn json_roundtrip_rejects_foreign_schema() {
        let mut f = ReviewFile {
            title: "T".into(),
            ..Default::default()
        };
        f.publish(version("m.mp4", (24, 1), 5));
        let bytes = f.to_json().unwrap();
        let back = ReviewFile::from_json(&bytes).unwrap();
        assert_eq!(back, f);
        let bad = br#"{"schema":"other/v9","title":"x","versions":[],"links":[]}"#;
        assert!(ReviewFile::from_json(bad).is_err());
    }
}
